### ISSUE TITLE
select2-hint position calculation

### ISSUE THREAD

**Issue by kekel87** [plantain-00/select2-component#17]
There is a problem in the TOP calculation for the select2-subscript-wrapper.
Yet in the sources, this appears right.
Probably a LESS configuration problem.

#### Expected:
```css
select2.material .select2-subscript-wrapper {
    position: absolute;
    top: calc(100% - 1.72917em);
    font-size: 75%;
}
```

#### Actual:
```css
select2.material .select2-subscript-wrapper {
    position: absolute;
    top: calc(98.27083%);
    font-size: 75%;
}
```
